
# DIF dbt Config-Driven Data Quality Solution v1.5
# Config-driven testing with elementary and dbt-artifacts integration

name: 'dif_ops_dq'
version: '1.5.0'
config-version: 2

dbt-cloud:
    project-id: 70471823549409

profile: 'dif_snowflake'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Variables for DIF integration
vars:
  # DIF Control Plane configuration
  dif_database: 'DB_GOVERNANCE'
  dif_config_schema: 'CONFIG_CONTROLS'
  dif_audit_schema: 'AUDIT_CONTROLS'
  
  # Default rule group (override at runtime with --vars)
  # Example: dbt run --vars '{"rule_group": "STAGING_VALIDATION"}'
  rule_group: 'DEFAULT'
  
  # Severity mapping (DIF severity → dbt severity)
  severity_mapping:
    CRITICAL: error
    HIGH: error
    MEDIUM: warn
    LOW: warn
    INFO: warn
  
  # Elementary package configuration
  elementary:
    elementary_database: DB_GOVERNANCE
    elementary_schema: ELEMENTARY
  
  # dbt_artifacts configuration
  dbt_artifacts:
    dbt_artifacts_database: DB_GOVERNANCE
    dbt_artifacts_schema: DBT_ARTIFACTS

# Default test configurations
tests:
  dif_ops_dq:
    +store_failures: true
    +schema: dbt_test_audit
    +severity: warn

# Model configurations
models:
  dif_ops_dq:
    dif_validation:
      +materialized: incremental
      +schema: DIF_TEST_RESULTS
      +tags: ['dif_v15']
    elementary_models:
      +enabled: true
      +schema: ELEMENTARY
    observability:
      +materialized: view
      +schema: DIF_OBSERVABILITY

# Post-run hook to sync results to DIF audit tables
on-run-end:
  - "{{ dif_sync_test_results_to_audit(results) }}"

# Seeds configuration
seeds:
  dif_ops_dq:
    +schema: DIF_SEEDS
