
# Schema definition for dif_validation models

version: 2

models:
  - name: dif_config_driven_tests
    description: |
      Dynamic test orchestration model for DIF v1.5.
      Executes tests based on rules loaded from CONFIG_CONTROLS.RULES table.
      
      **v1.5 Supported Rule Types:**
      - NULL_CHECK: Validates column null percentage
      - REFERENTIAL_INTEGRITY: Validates foreign key relationships
      - SUM_MATCH: Validates sum equality between source/target
      
      **Execution:**
      ```bash
      dbt run --select dif_config_driven_tests --vars '{"rule_group": "MY_RULE_GROUP"}'
      ```
    
    config:
      materialized: incremental
      unique_key: test_execution_id
      tags: ['dif_v15', 'config_driven']
      
    columns:
      - name: test_execution_id
        description: "Unique identifier for this test execution (run_id + rule_id)"
        tests:
          - not_null
          - unique
          
      - name: run_id
        description: "dbt invocation_id linking back to RUN_METADATA"
        tests:
          - not_null
          
      - name: rule_group
        description: "Rule group from --vars that was executed"
        
      - name: executed_at
        description: "Timestamp when test was executed"
        
      - name: dif_rule_id
        description: "DIF RULE_ID from CONFIG_CONTROLS.RULES"
        tests:
          - not_null
          
      - name: dif_rule_type
        description: "Rule type: NULL_CHECK, REFERENTIAL_INTEGRITY, SUM_MATCH"
        tests:
          - accepted_values:
              values: ['NULL_CHECK', 'REFERENTIAL_INTEGRITY', 'SUM_MATCH']
              severity: warn
              
      - name: test_status
        description: "Test outcome: PASS or FAIL"
        tests:
          - accepted_values:
              values: ['PASS', 'FAIL']
              
      - name: severity
        description: "DIF severity level mapped to dbt"

  - name: dif_test_results_summary
    description: |
      Aggregated view of test results by rule group and run.
      Useful for dashboards and monitoring.
