
# Schema for observability models

version: 2

models:
  - name: dif_dq_log_sync
    description: |
      Unified view of test results from elementary and dbt-artifacts.
      Syncs test outcomes to DIF-compatible format for audit logging.
    config:
      materialized: incremental
      schema: DIF_OBSERVABILITY
    columns:
      - name: log_key
        description: "Unique key for incremental loading"
        tests:
          - unique
          - not_null
      - name: run_id
        description: "dbt invocation_id"
      - name: rule_id
        description: "Extracted or generated rule ID"
      - name: rule_type
        description: "Inferred DIF rule type"
      - name: engine
        description: "Always 'DBT' for this model"
      - name: status
        description: "DIF status: PASS, FAIL, WARN, ERROR, SKIP"
      - name: start_time
        description: "Test execution start time"
      - name: end_time
        description: "Test execution end time"
      - name: synced_at
        description: "Timestamp when row was synced"
