
# Seeds schema definition

version: 2

seeds:
  - name: dif_sample_rules
    description: |
      Sample rule configurations for testing.
      Use this as a template for creating rules in CONFIG_CONTROLS.RULES.
    config:
      schema: DIF_SEEDS
      tags: ['sample', 'reference']
    columns:
      - name: rule_id
        description: "Unique rule identifier (prefix with RULE_)"
      - name: rule_group
        description: "Logical grouping for batch execution"
      - name: rule_type
        description: "Type: NULL_CHECK, REFERENTIAL_INTEGRITY, SUM_MATCH"
      - name: source_asset_id
        description: "FK to DATA_ASSETS - source table"
      - name: target_asset_id
        description: "FK to DATA_ASSETS - target table (for cross-asset rules)"
      - name: threshold_value
        description: "Pass/fail threshold"
      - name: threshold_type
        description: "ABSOLUTE, PERCENTAGE, BOOLEAN"
      - name: severity
        description: "CRITICAL, HIGH, MEDIUM, LOW, INFO"
      - name: rule_body
        description: "JSON configuration for rule parameters"
      - name: is_active
        description: "Enable/disable rule"
