
# Elementary source configuration for DIF control tables
# Provides observability and anomaly detection integration

version: 2

sources:
  - name: config_controls
    description: "DIF configuration control plane - rule definitions and metadata"
    database: "{{ var('dif_database', 'DB_GOVERNANCE') }}"
    schema: CONFIG_CONTROLS
    tables:
      - name: rules
        identifier: RULES
        description: "DIF rule configuration table - defines all validation rules"
        columns:
          - name: RULE_ID
            description: "Unique rule identifier"
            tests:
              - unique
              - not_null
          - name: RULE_GROUP
            description: "Logical grouping for batch execution"
            tests:
              - not_null
          - name: RULE_TYPE
            description: "Type of validation rule"
            tests:
              - not_null
              - accepted_values:
                  values: 
                    - 'NULL_CHECK'
                    - 'REFERENTIAL_INTEGRITY'
                    - 'SUM_MATCH'
                    - 'ROW_COUNT'
                    - 'ROW_COUNT_RANGE'
                    - 'DUPLICATE_CHECK'
                    - 'VALUE_RANGE'
                    - 'COMPLETENESS_CHECK'
                    - 'REGEX_PATTERN'
                    - 'SCHEMA_VALIDATION'
                    - 'DATA_FRESHNESS'
                    - 'CUSTOM_SQL'
                  severity: warn
          - name: SOURCE_ASSET_ID
            description: "Foreign key to DATA_ASSETS - source table for validation"
          - name: TARGET_ASSET_ID
            description: "Foreign key to DATA_ASSETS - target table for cross-asset rules"
          - name: IS_ACTIVE
            description: "Flag to enable/disable rules without deletion"
                  
      - name: data_assets
        identifier: DATA_ASSETS
        description: "Registry of data sources subject to quality checks"
        columns:
          - name: ASSET_ID
            description: "Unique asset identifier"
            tests:
              - unique
              - not_null
          - name: ASSET_PATH
            description: "Fully or partially qualified table/file path"
          - name: CONNECTION_NAME
            description: "Foreign key to CONNECTIONS table"
          - name: ASSET_TYPE
            description: "Type of asset: TABLE, FILE, S3_FILE, VIEW, QUERY"
        
      - name: connections
        identifier: CONNECTIONS
        description: "Database connection registry"
        columns:
          - name: CONNECTION_NAME
            description: "Unique connection identifier"
            tests:
              - unique
              - not_null
          - name: DB_TYPE
            description: "Database type: SNOWFLAKE, POSTGRES, S3, etc."
          - name: DATABASE_NAME
            description: "Default database for connection"

  - name: audit_controls
    description: "DIF audit control plane - execution logs and metrics"
    database: "{{ var('dif_database', 'DB_GOVERNANCE') }}"
    schema: AUDIT_CONTROLS
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}
    loaded_at_field: LOGGED_AT
    tables:
      - name: dq_log
        identifier: DQ_LOG
        description: "Test execution log - one row per test execution"
        columns:
          - name: LOG_ID
            description: "Auto-incrementing primary key"
          - name: RUN_ID
            description: "Foreign key to RUN_METADATA"
          - name: RULE_ID
            description: "Rule that was executed"
          - name: RULE_TYPE
            description: "Type of rule executed"
          - name: ENGINE
            description: "Execution engine: DBT, PYTHON, GLUE, SNOWFLAKE"
          - name: STATUS
            description: "Test outcome: PASS, FAIL, WARN, ERROR, SKIP"
          - name: LOGGED_AT
            description: "Timestamp of log entry"
        
      - name: run_metadata
        identifier: RUN_METADATA
        description: "Run summary metadata - one row per batch execution"
        columns:
          - name: RUN_ID
            description: "Unique run identifier (dbt invocation_id)"
          - name: RULE_GROUP
            description: "Rule group that was executed"
          - name: STATUS
            description: "Overall run status: RUNNING, PASS, FAIL, ERROR"
          - name: TOTAL_RULES
            description: "Total number of rules executed"
          - name: PASSED_RULES
            description: "Number of passed rules"
          - name: FAILED_RULES
            description: "Number of failed rules"
        
      - name: aggregation_log
        identifier: AGGREGATION_LOG
        description: "Computed aggregation values for reconciliation"
        columns:
          - name: AGGREGATION_LOG_ID
            description: "Auto-incrementing primary key"
          - name: RUN_ID
            description: "Foreign key to RUN_METADATA"
          - name: RULE_ID
            description: "Rule that computed this aggregation"
          - name: ASSET_SIDE
            description: "SOURCE or TARGET side of reconciliation"
          - name: AGGREGATION_TYPE
            description: "Type of aggregation: SUM, COUNT, AVG, etc."
          - name: AGGREGATION_VALUE
            description: "Computed aggregation value"
